feat/articles-pouringの仮実装
mamenz752/gadgelog pull request #12
Opened 2024-11-26 07:18 UTC by mk-619

ArticlePresenterのIkonの部分がエラーのままです

2024-11-27 01:32 UTC, mamenz752 reviewed
## TO DO
- 恐らくdata.jsonの`author`の部分の`imagePath`が`"img/hatake.jpg"`とか`"img/maeken.jpg"`のようになっているので、`"/aboutus/maeken.jpg"`のように直してください！（でもこれではエラーが直らないと思います...はたけのと組み合わせるとうまくいきます！）

1. `git branch`で`feat/articles-pouring`というところに印が付いていることを確認！
2. 今の箇所を修正して...
3. `git add .`して
4. `git commit -m`で`PR修正`というメッセージを記述してコミット！
5. `git push`したら教えてください👍

2024-11-27 04:29 UTC, mamenz752 requested changes
## この修正をしてできること
- `npm run start`をして`https://localhost:3000/articles/1`とか`https://localhost:3000/articles/2`にアクセスすると記事の内容が反映されます！

## TO DO
前のコメントで示したような手順で修正をして、`git commit -m "feat: ブログ記事データ取得実装"`でコミットをして`git push`してね！

2024-11-27 04:29 UTC, mamenz752 commented on src/components/layouts/ArticlePresenter.jsx
8行目に`import { useParams } from 'react-router-dom';`という記述を追加してください！

2024-11-27 04:29 UTC, mamenz752 commented on src/components/layouts/ArticlePresenter.jsx
> +  const data =articles[0];
10行目を消して
```
const { id } = useParams();
const data = articles.find((data) => data.id === Number(id));
```
というコードに置き換えてください！

2024-11-27 07:53 UTC, mk-619 commented
前述の部分直してpushしました．確認お願いします！

2024-11-28 03:18 UTC, mamenz752 approved these changes
![LGTMeow](https://lgtm-images.lgtmeow.com/2024/11/28/00/5956d05d-ea09-4bc1-b29c-2d6ba646f783.webp)](https://lgtmeow.com)

2024-11-28 03:26 UTC, merged