記事を追加
mamenz752/gadgelog pull request #15
Opened 2024-12-03 07:11 UTC by WataruHatake

モニターアームの記事を追加しました。

2024-12-09 07:17 UTC, mamenz752 requested changes
修正箇所コメントしました！よろしくお願いします！

2024-12-09 07:17 UTC, mamenz752 commented on src/components/saya/CommentForm.jsx
> +    const res = await fetch("http://localhost:5500/api/comments", {
`http://localhost:5000`に直してほしいです！

2024-12-09 07:17 UTC, mamenz752 commented on src/components/saya/Comments.jsx
> +    const res = await fetch(`http://localhost:5500/api/comments/${articleId}`);
ここも`5000`に直してください！

2024-12-10 05:03 UTC, WataruHatake commented
修正と記事

2024-12-10 05:16 UTC, mamenz752 approved these changes
## 覚え書き
- `CommentForm.jsx`で`5500`ポートになっているかも！

[![LGTMeow](https://lgtm-images.lgtmeow.com/2022/05/03/14/e9c9e48f-e243-483a-a4ac-c7090efc50fe.webp)](https://lgtmeow.com)

2024-12-10 05:18 UTC, merged